In [1]:
import torch

In [10]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points, points.stride()

(tensor([[4., 1.],
         [5., 3.],
         [2., 1.]]),
 (2, 1))

In [5]:
second_point = points[1]
second_point, second_point.storage_offset()

(tensor([5., 3.]), 2)

In [13]:
pt2 = torch.tensor(list(range(24))).view(2,3,4)
pt2,pt2.stride()

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 (12, 4, 1))

In [9]:
s1 = pt2[2]
s1, s1.storage_offset(), s1.size(), s1.shape

(tensor([ 8,  9, 10, 11]), 8, torch.Size([4]), torch.Size([4]))

In [19]:
pt3 = torch.tensor(list(range(2*3))).view(2,3)
pt3_t = pt3.t()
pt3, pt3_t, id(pt3.storage()) == id(pt3_t.storage())

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([[0, 3],
         [1, 4],
         [2, 5]]),
 True)

In [24]:
pt4 = torch.tensor(list(range(2*3*4))).view(2,3,4)
pt4, pt4.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 torch.Size([2, 3, 4]))

In [25]:
transpose_t = pt4.transpose(0, 2)
transpose_t, transpose_t.shape

(tensor([[[ 0, 12],
          [ 4, 16],
          [ 8, 20]],
 
         [[ 1, 13],
          [ 5, 17],
          [ 9, 21]],
 
         [[ 2, 14],
          [ 6, 18],
          [10, 22]],
 
         [[ 3, 15],
          [ 7, 19],
          [11, 23]]]),
 torch.Size([4, 3, 2]))

In [26]:
pt4.is_contiguous(), transpose_t.is_contiguous()

(True, False)

In [29]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [35]:
points = torch.ones(3, 4)
points_np = points.numpy()
points, points_np,


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

In [36]:
id(points),id(points_np)

(2411626731136, 2411669971856)