In [2]:
import numpy as np
import torch
from transformers import AutoModelForSequenceClassification
torch.set_printoptions(edgeitems=2, precision=2, linewidth=75)

### Models expect a batch of inputs

In [3]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [4]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

In [5]:
sequence = "I've been waiting for a HuggingFace course my whole life."

In [12]:
tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor([ids])

In [13]:
input_ids, input_ids.shape

(tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
           2607,  2026,  2878,  2166,  1012]]),
 torch.Size([1, 14]))

In [15]:
output = model(input_ids)

In [18]:
output, output.logits.shape

(SequenceClassifierOutput(loss=None, logits=tensor([[-2.73,  2.88]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None),
 torch.Size([1, 2]))

In [21]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence1_ids = [[200, 200, 200]]
sequence2_ids = [[200, 200]]
batched_ids = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id],
]

print(model(torch.tensor(sequence1_ids)).logits)
print(model(torch.tensor(sequence2_ids)).logits)
print(model(torch.tensor(batched_ids)).logits)

tensor([[ 1.57, -1.39]], grad_fn=<AddmmBackward0>)
tensor([[ 0.58, -0.41]], grad_fn=<AddmmBackward0>)
tensor([[ 1.57, -1.39],
        [ 1.34, -1.22]], grad_fn=<AddmmBackward0>)


In [22]:
attention_mask = [
    [1, 1, 1],
    [1, 1, 0],
]
outputs = model(torch.tensor(batched_ids), attention_mask=torch.tensor(attention_mask))

In [23]:
outputs.logits, outputs.logits.shape

(tensor([[ 1.57, -1.39],
         [ 0.58, -0.41]], grad_fn=<AddmmBackward0>),
 torch.Size([2, 2]))