In [1]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, precision=2, linewidth=100)

In [2]:
import csv
wine_path = "../data/p1ch4/tabular-wine/winequality-white.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";",skiprows=1)

In [3]:
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [4]:
result = csv.reader(open(wine_path), delimiter=';')
result

In [5]:
# 这里使用next的作用是将csv读取的reader对象转换为一个iter对象，即可以进行迭代操作
col_list = next(csv.reader(open(wine_path), delimiter=';'))
wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [6]:
# 转换为tensor对象
wineq = torch.from_numpy(wineq_numpy)
wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [7]:
#选择所有行，所有列，排除最后一列
data = wineq[:, :-1]
data, data.shape

(tensor([[ 7.00,  0.27,  ...,  0.45,  8.80],
         [ 6.30,  0.30,  ...,  0.49,  9.50],
         ...,
         [ 5.50,  0.29,  ...,  0.38, 12.80],
         [ 6.00,  0.21,  ...,  0.32, 11.80]]),
 torch.Size([4898, 11]))

In [8]:
#选择所有行的最后一列
target = wineq[:, -1].long()
target, target.shape, target.dtype

(tensor([6, 6,  ..., 7, 6]), torch.Size([4898]), torch.int64)

In [9]:
target.unsqueeze(1)

tensor([[6],
        [6],
        ...,
        [7],
        [6]])

In [10]:
target_onehot = torch.zeros(target.shape[0], 10)
target_onehot.scatter_(1, target.unsqueeze(1), 1.0)

tensor([[0., 0.,  ..., 0., 0.],
        [0., 0.,  ..., 0., 0.],
        ...,
        [0., 0.,  ..., 0., 0.],
        [0., 0.,  ..., 0., 0.]])

In [24]:
# 计算data每一列的均值
data_mean = torch.mean(data, dim=0)
data_mean, data.shape

(tensor([6.85e+00, 2.78e-01, 3.34e-01, 6.39e+00, 4.58e-02, 3.53e+01, 1.38e+02, 9.94e-01, 3.19e+00,
         4.90e-01, 1.05e+01]),
 torch.Size([4898, 11]))

In [12]:
import numpy as np
a1= np.array([0,0,5,5])
a2= np.array([2,2,3,3])

In [13]:
#ddof = 1代表样本的方差和标准差
a1.var(ddof=1) , a2.var(ddof=1)

(8.333333333333334, 0.3333333333333333)

In [14]:
a1.std(ddof=1) ,a2.std(ddof=1)

(2.886751345948129, 0.5773502691896257)

In [16]:
a = np.array([21,29,24,18,16,15])

In [17]:
#计算均值
a.mean()

20.5

In [19]:
#计算样本标准差
a.std(ddof=1)

5.319774431308154